//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDTDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OrderTemp
    {
        public int OrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Delivered { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<int> CustomerInforID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> TotalOrder { get; set; }
    }
}
